# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'udpserver.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1368, 858)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(420, 60, 201, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(720, 60, 191, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 140, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 180, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 230, 101, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 280, 101, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 330, 101, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(50, 380, 101, 17))
        self.label_6.setObjectName("label_6")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(160, 130, 211, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(160, 180, 211, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_3.setGeometry(QtCore.QRect(160, 230, 211, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_4.setGeometry(QtCore.QRect(160, 280, 211, 31))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_5.setGeometry(QtCore.QRect(160, 320, 211, 31))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_6.setGeometry(QtCore.QRect(160, 370, 211, 31))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_7.setGeometry(QtCore.QRect(160, 420, 211, 31))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(50, 420, 101, 17))
        self.label_8.setObjectName("label_8")
        self.textBrowser_8 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_8.setGeometry(QtCore.QRect(40, 470, 391, 351))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_9.setGeometry(QtCore.QRect(460, 470, 381, 351))
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.textBrowser_10 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_10.setGeometry(QtCore.QRect(870, 470, 391, 351))
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(60, 450, 61, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(470, 170, 67, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(430, 220, 101, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(450, 270, 101, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(460, 370, 101, 17))
        self.label_13.setObjectName("label_13")
        self.textBrowser_11 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_11.setGeometry(QtCore.QRect(570, 310, 211, 31))
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(460, 410, 101, 17))
        self.label_14.setObjectName("label_14")
        self.textBrowser_12 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_12.setGeometry(QtCore.QRect(570, 220, 211, 31))
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.textBrowser_13 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_13.setGeometry(QtCore.QRect(570, 360, 211, 31))
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(470, 440, 61, 17))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(460, 130, 67, 17))
        self.label_16.setObjectName("label_16")
        self.textBrowser_14 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_14.setGeometry(QtCore.QRect(570, 120, 211, 31))
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.textBrowser_15 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_15.setGeometry(QtCore.QRect(570, 270, 211, 31))
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.textBrowser_16 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_16.setGeometry(QtCore.QRect(570, 170, 211, 31))
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.textBrowser_17 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_17.setGeometry(QtCore.QRect(570, 410, 211, 31))
        self.textBrowser_17.setObjectName("textBrowser_17")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(460, 320, 101, 17))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(870, 260, 101, 17))
        self.label_18.setObjectName("label_18")
        self.textBrowser_18 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_18.setGeometry(QtCore.QRect(970, 400, 211, 31))
        self.textBrowser_18.setObjectName("textBrowser_18")
        self.textBrowser_19 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_19.setGeometry(QtCore.QRect(970, 110, 211, 31))
        self.textBrowser_19.setObjectName("textBrowser_19")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(870, 310, 101, 17))
        self.label_19.setObjectName("label_19")
        self.textBrowser_20 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_20.setGeometry(QtCore.QRect(970, 300, 211, 31))
        self.textBrowser_20.setObjectName("textBrowser_20")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(850, 210, 101, 17))
        self.label_20.setObjectName("label_20")
        self.textBrowser_21 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_21.setGeometry(QtCore.QRect(970, 210, 211, 31))
        self.textBrowser_21.setObjectName("textBrowser_21")
        self.textBrowser_22 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_22.setGeometry(QtCore.QRect(970, 260, 211, 31))
        self.textBrowser_22.setObjectName("textBrowser_22")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(870, 360, 101, 17))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(870, 400, 101, 17))
        self.label_22.setObjectName("label_22")
        self.textBrowser_23 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_23.setGeometry(QtCore.QRect(970, 350, 211, 31))
        self.textBrowser_23.setObjectName("textBrowser_23")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(860, 440, 61, 17))
        self.label_23.setObjectName("label_23")
        self.textBrowser_24 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_24.setGeometry(QtCore.QRect(970, 160, 211, 31))
        self.textBrowser_24.setObjectName("textBrowser_24")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(880, 120, 67, 17))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(890, 160, 67, 17))
        self.label_25.setObjectName("label_25")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Start"))
        self.pushButton_2.setText(_translate("Dialog", "stop"))
        self.label.setText(_translate("Dialog", "模拟/数字"))
        self.label_2.setText(_translate("Dialog", "通道号"))
        self.label_3.setText(_translate("Dialog", "采样的点个数"))
        self.label_4.setText(_translate("Dialog", "报文长度"))
        self.label_5.setText(_translate("Dialog", "超时表示"))
        self.label_6.setText(_translate("Dialog", "校验计数错误"))
        self.label_8.setText(_translate("Dialog", "UDP包序号"))
        self.label_9.setText(_translate("Dialog", "数据部分:"))
        self.label_10.setText(_translate("Dialog", "通道号"))
        self.label_11.setText(_translate("Dialog", "采样的点个数"))
        self.label_12.setText(_translate("Dialog", "报文长度"))
        self.label_13.setText(_translate("Dialog", "校验计数错误"))
        self.label_14.setText(_translate("Dialog", "UDP包序号"))
        self.label_15.setText(_translate("Dialog", "数据部分:"))
        self.label_16.setText(_translate("Dialog", "模拟/数字"))
        self.label_17.setText(_translate("Dialog", "超时表示"))
        self.label_18.setText(_translate("Dialog", "报文长度"))
        self.label_19.setText(_translate("Dialog", "超时表示"))
        self.label_20.setText(_translate("Dialog", "采样的点个数"))
        self.label_21.setText(_translate("Dialog", "校验计数错误"))
        self.label_22.setText(_translate("Dialog", "UDP包序号"))
        self.label_23.setText(_translate("Dialog", "数据部分:"))
        self.label_24.setText(_translate("Dialog", "模拟/数字"))
        self.label_25.setText(_translate("Dialog", "通道号"))
